digital_input_dict = {
    "FACTORY I/O (Running)": False,
    "Group Start": False,
    "Group Stop": False,
    "Input 3": False,
    "Input 4": False,
    "Input 5": False,
    "Input 6": False,
    "Input 7": False,
    "Input 8": False,
    "Input 9": False,
    "Input Conveyor 1 B1": False,
    "Scale Conveyor 1 B1": False,
    "Output Conveyor 1 B1": False,
    "Input 13": False,
    "Input 14": False,
    "Input 15": False,
    "Input 16": False,
    "Input 17": False,
    "Input 18": False,
    "Input 19": False,
    "Output Conveyor Encoder A": False,
    "Input 21": False,
    "Input 22": False,
    "Input 23": False,
    "Input 24": False,
    "Input 25": False,
    "Input 26": False,
    "Input 27": False,
    "Input 28": False,
    "Input 29": False,
    "Input 30": False,
    "Input 31": False,
}

digital_output_dict = {
    "Group Stopped": False,
    "Group Starting": False,
    "Group Running": False,
    "Start Lamp": False,
    "Stop Lamp": False,
    "Output 5": False,
    "Output 6": False,
    "Output 7": False,
    "Output 8": False,
    "Output 9": False,
    "Sweeper 1 Arm": False,
    "Sweeper 2 Arm": False,
    "Sweeper 3 Arm": False,
    "Output 13": False,
    "Output 14": False,
    "Product Spawn": False,
    "Output 16": False,
    "Output 17": False,
    "Output 18": False,
    "Output 19": False,
    "Input Conveyor 1 (F)": False,
    "Scale Conveyor 1 (F)": False,
    "Output Conveyor 1 (F)": False,
    "Output Conveyor 2 (F)": False,
    "Small Box Conveyor 1 (F)": False,
    "Medium Box Conveyor 1 (F)": False,
    "Large Box Conveyor 1 (F)": False,
    "Sweeper 1 Motor (F)": False,
    "Sweeper 2 Motor (F)": False,
    "Sweeper 3 Motor (F)": False,
    "Output 30": False,
    "Output 31": False,
}